"""drop unused columns

Revision ID: 1.1
Revises: 1.0
Create Date: 2022-08-29 22:00:34.637699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.1'
down_revision = '1.0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'from_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('from_ad', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
