"""add new columns to user table

Revision ID: 1.2
Revises: 1.1
Create Date: 2022-09-04 20:17:46.985107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.2'
down_revision = '1.1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'address')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
